### PR TITLE
Add Code Climate configurations

### PR DESCRIPTION
**Pull request by glauco**

### CODE REVIEW

**Comment by waldemarnt** [comment]
👍

**Comment by bltavares** [comment]
Should we already add the badge on this commit?

**Comment by glauco** [comment]
I would love to, but Code Climate does not let me doing so.

Their eslint just breaks in the middle of the process.

https://codeclimate.com/github/agco-fuse/dealership-demo-node/builds/1

**Comment by bltavares** [comment]
Ok! We can do that on a follow up.

**Pull request merged**
